# Generated by Django 6.0.3 on 2026-03-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('stolen', 'Угон'), ('arrest', 'Арест'), ('ban_registration', 'Запрет регистрационных действий'), ('pledge', 'Залог'), ('wanted', 'В розыске')], max_length=30, verbose_name='Тип ограничения')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('initiator', models.CharField(blank=True, max_length=200, verbose_name='Инициатор (суд, пристав, полиция)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
                'ordering': ['-start_date'],
            },
        ),
    ]
